### ISSUE TITLE
create plotting tab

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/Electron-Sight#32]
For demo in Jan, Joshua recommended a separate plotting tab that would displace summary statistics of classified regions, potential plots include:
 - (@joshua can you fill this out)

**Comment by JABull1066** [comment]
Some ideas for plots to include:
- Numbers of cells in each region (e.g., in different regions as boxplot)
- Cell densities (e.g., in different regions as boxplot)
- Distributions of distance between NN cells
- Distributions of distance between randomly chosen point and nearest cell (Spherical Contact Distance - SCD)
- Differences between these things in different annotated regions (e.g., annotating 2 distinct regions and quickly viewing the comparison)

We can also display a lot of stats just in a table, e.g. total area of positively / negatively stained tissue, total area of annotated region, percentage of regions which is +ve or -ve, etc. . I think graphs are most useful for comparison purposes (e.g., between different regions of an image) but think having visual guide could be very persuasive to users

**Comment by martinjrobins** [comment]
at the moment we just classify superpixels into cell / not-cell. How do you get different classes of cell, multiple svm classifiers?

**Comment by martinjrobins** [comment]
Meeting 13th Dec - @martinjrobins and @JABull1066 

We will implement one pipeline
1. open app
2. train a classifier (as currently exists)
3. draw multiple regions (annotations)
4. Predict: choose a classifier, click go -> applies classifier to *all* regions
5. Apply watershed algorithm to classification mask to find single cells
6. Draw as many plots as we can (see above)

**Comment by martinjrobins** [comment]
@JABull1066: I'm a bit confused about the watershed algorithm. It is a segmentation algorithm right? So how do you use that to find the centre of cells? In fact the watershed algorithm uses a set of marker pixels, one for each cell/region, so how do you normally find these?

**Comment by JABull1066** [comment]
@martinjrobins sorry, have only just spotted this! The process I currently use is basically as given in this blog post - the idea is essentially to use the minima in the distance transform to give the approximate cell centre. Practically, what I then do at the moment is to divide each identified "cell" in two until it falls within the expected size range for the given cell type. Did I send you the function "IdentifyCellsViaWatershed_DependentOnSize.m" ? 

https://blogs.mathworks.com/steve/2013/11/19/watershed-transform-question-from-tech-support/

**Comment by martinjrobins** [comment]
@JABull1066 : I can't find the file you mentioned "IdentifyCellsViaWatershed_DependentOnSize.m" in the code that you shared with me. Can you attach it to this issue?

**Comment by JABull1066** [comment]
It won't seem to let me attach the .m file, I'll email it to you!

**Comment by martinjrobins** [comment]
@JABull1066: how are you going on the plotting tab? We could meet up and look at it together if that would help?

**Comment by JABull1066** [comment]
Thanks @martinjrobins, I think meeting soon would probably be useful - I've been a bit swamped by papers recently so haven't managed to get a good look at the code for a while!

**Comment by martinjrobins** [comment]
no problem, I know the feeling! Let me know when you are a bit more free and we can organise a time to meet

**Comment by martinjrobins** [comment]
meeting with joshua 4th march

- plotting tab should be a new window

**Comment by martinjrobins** [comment]
closed via #54
