### ISSUE TITLE
use redux for state

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/Electron-Sight#38]
The app currently needs to store:
- A classifier in the process of being built
- A set of already built classifiers
- An annotation in the process of being built
- A set of annotations already built
- A set of annotation+classifier which contain the results of a classifier used on a given annotated area

Where should this be stored?
1. In Menu, and passed down to other react classes via props?
2. Using something like redux?

I'm leaning towards 2 so I can learn how redux works....

**Comment by iamleeg** [comment]
I'd vote for redux, too. There are then good patterns for getting events out of the UI and into the "reducer", which is the function that updates the application state.

**Comment by iamleeg** [comment]
BTW take a look at the [ducks pattern](https://medium.com/@scbarrus/the-ducks-file-structure-for-redux-d63c41b7035c) for organizing redux apps. But learn about redux first, or that article won't make much sense :)

**Comment by martinjrobins** [comment]
ok, I'll have a go at this using the ducks pattern
